### ISSUE TITLE
Hjort & Glad: Other bandwidth selection methods.

### ISSUE THREAD

**Issue by JonasMoss** [JonasMoss/kdensity#10]
Hjort & Glad discussed several bw selection methods: Should we implement them? (before launch?)

If so, maybe make one issue for each.

**Comment by Tveten** [comment]
I can try to implement bandwidth selection by cross-validation as I guess it's the method that will work best for all kernels and starts?

**Comment by JonasMoss** [comment]
@Tveten That would be great!  👍 

I don't know the technicalities of this. Do you think it is possible to implement it for *any* choice of kernel function? In that case, we would take care of all asymmetric kernels and parametric starts in one big swoop. Don't be afraid of `integrate` if that's needed. The interface is made so that new kernels can be tried out with virtually no work - combine this with a general UCV and we have something great!
