### ISSUE TITLE
Fix normalization.

### ISSUE THREAD

**Issue by Tveten** [JonasMoss/kdensity#45]
When testing kdensity today, I got some densities with values of around 10^40 over an interval of length 20 on the x axis by using the default settings. Setting normalized = FALSE fixed the issue. Other starts than the uniform, however, need normalization to work properly.

**Comment by Tveten** [comment]
[kdens_feil.txt](https://github.com/JonasMoss/kdensity/files/3038926/kdens_feil.txt)

**Comment by JonasMoss** [comment]
I'm adding an error message to the "paperversion" branch.
