### ISSUE TITLE
[JOSS Review] summary method

### ISSUE THREAD

**Issue by gvegayon** [JonasMoss/kdensity#49]
Part of JOSS review openjournals/joss-reviews#1566

This is more style than anything, but I think it would be nice it the computed quantities were returned instead of actual object in `summary.kdensity`.

**Comment by JonasMoss** [comment]
The computed quantities are all available in the object itself. The summary function only works as an extended print, it does no computations itself. E.g. the bandwidth is available in object$bw_str etc.
