### ISSUE TITLE
[JOSS Review] Related R packages

### ISSUE THREAD

**Issue by gvegayon** [JonasMoss/kdensity#51]
Part of JOSS review openjournals/joss-reviews#1566

I think it is important to list and point out differences with other R packages that may perform a similar task, e.g.:

- [kdcopula](https://cran.r-project.org/package=kdecopula/) for copula bivariate kernel density.
- [kde1d](https://cran.r-packages.org/package=kde1d) for bounded univariate kernel density.
- [Ake](https://cran.r-packages.org/package=Ake) and [ks](https://cran.r-packages.org/package=ks) which implement the Beta kernel of Chen (1999).
- etc.

This should be somehow reflected in both the README.(R)md file and the paper.md file.

**Comment by JonasMoss** [comment]
Updated readme in 9acec1b707e91fc521437aa4d1f6ecacda2cb0a8. Will look at the paper too.

**Comment by JonasMoss** [comment]
Updated the paper too. I think think the main difference between this package and all others is that this one uses parametric starts.

**Comment by gvegayon** [comment]
That's nice. Thanks. You need to fix one of the links (see note on commit).
