### ISSUE TITLE
[JOSS Review] Contribution/bug report guidelines

### ISSUE THREAD

**Issue by gvegayon** [JonasMoss/kdensity#52]
Part of JOSS review openjournals/joss-reviews#1566

The package should have explicit guidelines for contributing to the project/asking questions/reporting bugs. See https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines

**Comment by JonasMoss** [comment]
Thanks! I added some guidelines in b98b0aecc1143260894b87120fbc7419faef7d74.
