### ISSUE TITLE
[JOSS Review]: Installation instructions: missing dependency: EQL

### ISSUE THREAD

**Issue by trashbirdecology** [JonasMoss/kdensity#56]
JOSS Review [1566](https://github.com/openjournals/joss-reviews/issues/1566)

Either add as a depends or specify the dependency in the README for package `EQL`

`Error: The bandwidth function 'RHE' requires the package 'EQL' to work.`

**Comment by JonasMoss** [comment]
Added EQL as an import in 934b0b98ce9e31def79f30f3f30ab2fe5d5b0e0c.
