### ISSUE TITLE
JOSS Review 1566 Function kdensity.R review

### ISSUE THREAD

**Issue by trashbirdecology** [JonasMoss/kdensity#59]
### JOSS Review [1566](https://github.com/openjournals/joss-reviews/issues/1566)

In the function `kdensity.R`, you have a stop command if NAs are present in X. The line following the stop command removes NAs. So either replace 'stop' with 'warning' or 'message', or remove ` x = x[!is.na(x)] entirely:

```
if(has.na) {
    if(!na.rm) stop("x contains NAs and na.rm = FALSE.")
    x = x[!is.na(x)]
  }
```
---------------
 Consider removing the word "massage":
>  Now we massage and handle the combinations of kernel, start and support.
---------------
Consider adding error or message,  or a default value for @param: start, or remove NULL default for @param:start. If start=NULL, function will fail at line:
> kss_list = get_kernel_start_support(kernel, start, support)

**Comment by JonasMoss** [comment]
The first issue is intended, as x = x[!is.na(x)] is never seen when the function is stopped, but is seen if it isn't. Take e.g.

```
f = function(x, na.rm = FALSE) {
  
  has.na = any(is.na(x))
  
  if(has.na) {
    if(!na.rm) stop("x contains NAs and na.rm = FALSE.")
    x = x[!is.na(x)]
  }

  x
  
}

> f(0, na.rm = TRUE)
[1] 0
> f(c(NA, 0), na.rm = TRUE)
[1] 0
> f(c(NA, 0), na.rm = FALSE)
Error in f(c(NA, 0), na.rm = FALSE) : x contains NAs and na.rm = FALSE.
```

I changed the code in 5747aa0 to make it clearer.

---
Removed "massage" in 4a515f52c63edc651b52daf5db22a71acfb98665.

---
Do you have an example of when the function fails? When I run it with only `NULL` it works:

```
> kdensity:::get_kernel_start_support(kernel = NULL, start = NULL, support = NULL)
$kernel
$kernel$kernel
function(y, x, h) stats::dnorm((y-x)/h)
<environment: namespace:kdensity>
...
```
